/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package us.praefectus.scorebored.swing;

import java.awt.Component;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author mcgann
 */
public class StackTraceDialog extends javax.swing.JDialog {

    /**
     * Creates new form StackTraceDialog
     */
    public StackTraceDialog(Throwable error) {
        super((JFrame)null, true);
        initComponents();
        
        Throwable currentFrame = error;
        List<Throwable> errors = new LinkedList<Throwable>();
        while ( currentFrame != null ) {
            errors.add(currentFrame);
            currentFrame = currentFrame.getCause();
        }
        
        exceptionList.setListData(errors.toArray(new Throwable[] {}));
        exceptionList.setCellRenderer(new DefaultListCellRenderer() { 
            @Override
            public Component getListCellRendererComponent(JList list,
                    Object value, int index, boolean isSelected,
                    boolean cellHasFocus) {
                return super.getListCellRendererComponent(list, 
                        ((Throwable)value).getClass().getName(), index, 
                        isSelected, cellHasFocus);
            }          
        });
        exceptionList.setSelectedIndex(0);
    }

    private void refreshStackTrace() {
        Throwable error = (Throwable)exceptionList.getSelectedValue();
        StringBuilder sb = new StringBuilder();
        sb.append(error.toString());
        sb.append("\n");
        for ( StackTraceElement element: error.getStackTrace() ) {
            sb.append("\t");
            sb.append(element.toString());
            sb.append("\n");
        }
        stackTraceText.setText(sb.toString());
        stackTraceText.setCaretPosition(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        exceptionList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        stackTraceText = new javax.swing.JTextArea();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stack Trace");

        exceptionList.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        exceptionList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        exceptionList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                exceptionListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(exceptionList);

        stackTraceText.setColumns(20);
        stackTraceText.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        stackTraceText.setRows(5);
        jScrollPane2.setViewportView(stackTraceText);

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(continueButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(continueButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_continueButtonActionPerformed

    private void exceptionListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_exceptionListValueChanged
        refreshStackTrace();
    }//GEN-LAST:event_exceptionListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JList exceptionList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea stackTraceText;
    // End of variables declaration//GEN-END:variables
}
